export const QUOTES = [
  "Don't Panic",
  "Time is an illusion. Lunchtime doubly so.",
  "The ships hung in the sky in much the same way that bricks don't.",
  "In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.",
  "A towel is about the most massively useful thing an interstellar hitchhiker can have.",
  "The knack of flying is learning how to throw yourself at the ground and miss.",
  "The Answer to the Great Question of Life, the Universe and Everything is... forty-two.",
  "The Guide is definitive. Reality is frequently inaccurate.",
  "Anything that happens, happens. Anything that, in happening, causes something else to happen, causes something else to happen.",
  "The Hitchhiker's Guide to the Galaxy has a few things to say on the subject of towels.",
  "I never could get the hang of Thursdays.",
  "This must be Thursday. I never could get the hang of Thursdays.",
  "All through my life I've had this strange unaccountable feeling that something was going on in the world, and no one told me what it was.",
  "You know, it's at times like this, when I'm trapped in a Vogon airlock with a man from Betelgeuse, and about to die of asphyxiation in deep space, that I really wish I'd listened to what my mother told me when I was young.",
  "My doctor says that I have a malformed public-duty gland and a natural deficiency in moral fibre.",
  "I don't understand, it's filled with stars.",
  "This is obviously some strange usage of the word 'safe' that I wasn't previously aware of.",
  "I could never get the hang of Thursdays.",
  "This is the sort of thing that would really get right on my nerves if I had any.",
  "I refuse to answer that question on the grounds that I don't know the answer.",
  "Time is an illusion. Lunchtime doubly so.",
  "You'd better be prepared for the jump into hyperspace. It's unpleasantly like being drunk.",
  "What's so unpleasant about being drunk? — Ask a glass of water.",
  "It's easier to resist at the beginning than at the end.",
  "Six pints of bitter and quickly, please — the world's about to end.",
  "He's spending a year dead for tax reasons.",
  "If there's anything more important than my ego around, I want it caught and shot now.",
  "Life's bad enough as it is without wanting to invent any more of it.",
  "Don't worry. They've got to build it before they can destroy it.",
  "It's not the fall that kills you; it's the sudden stop at the end.",
  "If there's anything more important than my ego around, I want it caught and shot now.",
  "Zaphod's just this guy, you know?",
  "I'm so hip I have difficulty seeing over my own pelvis.",
  "Ten out of ten for style, but minus several million for good thinking.",
  "If I asked you where the hell we were, would I regret it?",
  "Okay, so ten out of ten for style, but minus several million for good thinking.",
  "I demand that I may or may not be Viceroy of the Universe.",
  "I don't believe it! Prove it to me and I still won't believe it.",
  "Who's Zaphod Beeblebrox? Oh, that's me, baby.",
  "Hey, this is terrific! Someone down there is trying to kill us!",
  "Here I am, brain the size of a planet, and they ask me to take you down to the bridge. Call that job satisfaction? 'Cause I don't.",
  "I think you ought to know I'm feeling very depressed.",
  "I'd make a suggestion, but you wouldn't listen. No one ever does.",
  "Life. Don't talk to me about life.",
  "I've calculated your chances of survival, but I don't think you'll like it.",
  "The first ten million years were the worst. The second ten million years, they were the worst too. The third ten million years I didn't enjoy at all.",
  "I'm not getting you down at all, am I?",
  "Funny, how just when you think life can't possibly get any worse, it suddenly does.",
  "Do you want me to sit in a corner and rust or just fall apart where I'm standing?",
  "Pardon me for breathing, which I never do anyway, so I don't know why I bother to say it.",
  "The Answer to Life, the Universe, and Everything is 42.",
  "I speak of normality as if it were some kind of virtue.",
  "There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable.",
  "There is another theory which states that this has already happened.",
  "Curiously enough, the only thing that went through the mind of the bowl of petunias as it fell was 'Oh no, not again.'",
  "Beware of the Leopard.",
  "Mostly harmless.",
  "The Guide says that the best drink in existence is the Pan Galactic Gargle Blaster.",
  "The effect of a Pan Galactic Gargle Blaster is like having your brain smashed out by a slice of lemon wrapped round a large gold brick.",
  "Resistance is useless!",
  "Space is big. Really big. You just won't believe how vastly, hugely, mind-bogglingly big it is.",
  "It's not so much an afterlife as a sort of afterlunch.",
  "We demand rigidly defined areas of doubt and uncertainty!",
  "If you try to take a cat apart to see how it works, the first thing you have on your hands is a non-working cat.",
  "Human beings, who are almost unique in having the ability to learn from the experience of others, are also remarkable for their apparent disinclination to do so.",
  "Nothing travels faster than the speed of light with the possible exception of bad news.",
  "The last ever dolphin message was misinterpreted as a surprisingly sophisticated attempt to do a double backward somersault through a hoop while whistling the 'Star Spangled Banner'. But in fact the message was this: 'So long and thanks for all the fish.'",
  "No point in driving yourself mad trying to stop yourself going mad.",
  "Anyone who is capable of getting themselves made President should on no account be allowed to do the job.",
  "You live and learn. At any rate, you live.",
  "The Guide warns that once you've seen one planet completely destroyed, seeing it again is rather less impressive.",
  "You may not instantly see why I'm wrong, but trust me, I am.",
  "Reality is frequently inaccurate.",
  "For a moment, nothing happened. Then, after a second or so, nothing continued to happen.",
  "The babel fish is small, yellow, leech-like, and probably the oddest thing in the universe.",
  "By effectively removing all barriers to communication between different races and cultures, the babel fish has caused more and bloodier wars than anything else in the history of creation.",
  "It is a mistake to think you can solve any major problems just with potatoes.",
  "He felt that his whole life was some kind of dream and he sometimes wondered whose it was and whether they were enjoying it.",
  "The major problem—one of the major problems, for there are several—one of the many major problems with governing people is that of whom you get to do it.",
  "And so the universe came to an end — not with a bang, but with a slight sense of disappointment.",
  "It is a mistake to think you can solve any major problems just with potatoes.",
  "You may not have noticed, but the Universe is a very dangerous place.",
  "He felt that his whole life was some kind of dream and he sometimes wondered whose it was and whether they were enjoying it.",
  "Arthur blinked at the screens. The universe blinked back.",
  "The universe is big. It's vast and complicated and ridiculous.",
  "He hoped and prayed that there wasn't an afterlife. Then he realized there was a contradiction involved here and merely hoped that there wasn't an afterlife.",
  "The story so far: In the beginning the Universe was created...",
  "The Guide is definitive. Reality is frequently inaccurate.",
  "A learning experience is one of those things that say, 'You know that thing you just did? Don't do that.'",
  "We apologize for the inconvenience.",
  "He was a man who always assumed that he was right, which occasionally made him wrong.",
  "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.",
  "He felt that his whole life was some kind of dream and he sometimes wondered whose it was and whether they were enjoying it.",
  "I'm not getting you down at all, am I?",
  "I'd far rather be happy than right any day.",
  "We demand rigidly defined areas of doubt and uncertainty!",
  "He wondered if there was a time before lunch.",
  "I love deadlines. I love the whooshing noise they make as they go by.",
  "There is no point in pretending that you know what you are doing.",
  "So long, and thanks for all the fish."
];