CREATE TABLE IF NOT EXISTS mobile_app_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    event_type text NOT NULL,
    device_id text,
    app_version text,
    os_name text,
    os_version text,
    credit_balance integer,
    theme text
);

ALTER TABLE mobile_app_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous insert for app logs"
ON mobile_app_logs
FOR INSERT
TO anon
WITH CHECK (true);